language: java

jdk:
- openjdk10

before_install:
- test ! -f ~/.m2/settings.xml || rm ~/.m2/settings.xml

script: ./mvnw clean verify

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.m2/wrapper'
